#!/usr/bin/env bash
# ai-dev-baseline — gemini (Antigravity) adapter.
#
# Wires this repo's Antigravity payload (agents/gemini/GEMINI.md, generated by
# scripts/build.sh from base/practices/ — never edit it by hand) into
# Antigravity's user-global root config. Antigravity's `agy` CLI auto-loads
# ~/.gemini/GEMINI.md at the start of every session (base/roles.md: "gemini/
# Antigravity reads ~/.gemini/GEMINI.md + ~/.gemini/config/").
#
# Called by the top-level installer/uninstaller — do not run standalone unless
# you know what you're doing:
#   bash agents/gemini/adapter.sh install   <repo> <backup_dir>
#   bash agents/gemini/adapter.sh uninstall <repo>
#
# Portable to macOS bash 3.2: no `readlink -f`, no `mapfile`, no associative
# arrays.

set -uo pipefail

# Shared symlink/backup primitives (adb_info / adb_link / adb_unlink_if_ours) — the
# ONE home, sourced not copied. This adapter lives at agents/gemini/adapter.sh, so the
# repo's scripts/lib is two levels up.
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
. "$_here/../../scripts/lib/common.sh"

cmd_install() {
  local repo="$1" backup_dir="$2"
  mkdir -p "$HOME/.gemini"
  adb_link "$repo/agents/gemini/GEMINI.md" "$HOME/.gemini/GEMINI.md" "$backup_dir"
  adb_info "  note   ~/.gemini/settings.json and ~/.gemini/config/hooks.json are yours to manage — a sample hooks file lives at agents/gemini/config/hooks.sample.json"
}

cmd_uninstall() {
  local repo="$1"
  adb_unlink_if_ours "$HOME/.gemini/GEMINI.md" "$repo"
}

case "${1:-}" in
  install)
    shift
    if [ $# -lt 2 ]; then
      echo "usage: adapter.sh install <repo> <backup_dir>" >&2
      exit 2
    fi
    cmd_install "$1" "$2"
    ;;
  uninstall)
    shift
    if [ $# -lt 1 ]; then
      echo "usage: adapter.sh uninstall <repo>" >&2
      exit 2
    fi
    cmd_uninstall "$1"
    ;;
  *)
    echo "usage: adapter.sh <install|uninstall> ..." >&2
    exit 2
    ;;
esac
