#!/usr/bin/env bash
# ai-dev-baseline — gemini (Antigravity) adapter.
#
# Wires this repo's Antigravity payload (agents/gemini/GEMINI.md, generated by
# scripts/build.sh from base/practices/ — never edit it by hand) into
# Antigravity's user-global root config. Antigravity's `agy` CLI auto-loads
# ~/.gemini/GEMINI.md at the start of every session (base/roles.md: "gemini/
# Antigravity reads ~/.gemini/GEMINI.md + ~/.gemini/config/").
#
# Called by the top-level installer/uninstaller — do not run standalone unless
# you know what you're doing:
#   bash agents/gemini/adapter.sh install   <repo> <backup_dir>
#   bash agents/gemini/adapter.sh uninstall <repo>
#
# Runs on bash >= 5.3 (this repo's runtime floor — #255). It gates its own interpreter via
# adb_require_bash below, so an adapter invoked from a shell whose PATH resolves an older
# bash re-execs into a current one rather than failing somewhere deep.

set -uo pipefail

# Shared symlink/backup primitives (adb_info / adb_link / adb_unlink_if_ours) — the
# ONE home, sourced not copied. This adapter lives at agents/gemini/adapter.sh, so the
# repo's scripts/lib is two levels up.
_adb_boot_src="${BASH_SOURCE[0]}"; _adb_boot_rel="."
# ADB-BOOTSTRAP-BEGIN (#343) — BYTE-IDENTICAL IN EVERY ENTRY POINT; pinned by scripts/check-bootstrap.sh,
# which carries why each line is shaped this way. Lossless because `$(…)` strips every trailing newline:
# `${src%/*}` cannot strip, and the `X` sentinel bounds what the `pwd` capture can. Logical `pwd` (not
# `-P`) preserves how install.sh records its symlink targets. bash 3.2-safe: this runs before the gate.
_adb_boot_dir="${_adb_boot_src%/*}"
if [ "$_adb_boot_dir" = "$_adb_boot_src" ]; then _adb_boot_dir="."; elif [ -z "$_adb_boot_dir" ]; then _adb_boot_dir="/"; fi
_adb_boot_abs="$(cd -- "$_adb_boot_dir/$_adb_boot_rel" && pwd && printf 'X')"
_adb_boot_abs="${_adb_boot_abs%X}"; _adb_boot_abs="${_adb_boot_abs%$'\n'}"
[ -n "$_adb_boot_abs" ] || { printf '%s: FATAL - cannot resolve this clone location.\n' "${0##*/}" >&2; exit 1; }
# ADB-BOOTSTRAP-END
_here="$_adb_boot_abs"
# shellcheck source=/dev/null
. "$_here/../../scripts/lib/common.sh"
# bash 5.3 runtime floor (#256) — re-exec into a >= 5.3 interpreter, or exit with instructions.
adb_require_bash "$@"

cmd_install() {
  local repo="$1" backup_dir="$2" rc=0 manifest
  mkdir -p "$HOME/.gemini"
  # Link via the shared manifest (#48) — the same producer install.sh + bin/baseline consume,
  # so this adapter can't drift from them. Capture the status BEFORE the note print (adb_info
  # would otherwise overwrite $?), so a missing source makes the adapter — and the top-level
  # installer — exit non-zero.
  #
  # THE PRODUCER IS CAPTURED SEPARATELY (#324, D64): a `$(…)` inside the heredoc discarded its
  # status, so its refusal for an unrepresentable $repo/$HOME arrived as an empty manifest.
  manifest="$(adb_agent_manifest gemini "$repo" "$HOME")" || {
    adb_info "  ERROR  cannot enumerate the install surface — nothing was linked (see above)"
    return 1
  }
  adb_link_manifest "$backup_dir" <<EOF || rc=1
$manifest
EOF
  adb_info "  note   ~/.gemini/settings.json and ~/.gemini/config/hooks.json are yours to manage — a sample hooks file lives at agents/gemini/config/hooks.sample.json"
  return "$rc"
}

cmd_uninstall() {
  local repo="$1" manifest
  # Remove via the same shared manifest install linked from (#48), so this can't drift from
  # cmd_install even if gemini ever grows a second installed path. Same capture-then-check as
  # cmd_install — and a refusal removes NOTHING rather than acting on a map it just rejected.
  manifest="$(adb_agent_manifest gemini "$repo" "$HOME")" || {
    adb_info "  ERROR  cannot enumerate what to remove — NOTHING was unlinked (see above)"
    return 1
  }
  adb_unlink_manifest "$repo" <<EOF
$manifest
EOF
}

case "${1:-}" in
  install)
    shift
    if [ $# -lt 2 ]; then
      echo "usage: adapter.sh install <repo> <backup_dir>" >&2
      exit 2
    fi
    cmd_install "$1" "$2"
    ;;
  uninstall)
    shift
    if [ $# -lt 1 ]; then
      echo "usage: adapter.sh uninstall <repo>" >&2
      exit 2
    fi
    cmd_uninstall "$1"
    ;;
  *)
    echo "usage: adapter.sh <install|uninstall> ..." >&2
    exit 2
    ;;
esac
