#!/usr/bin/env bash
# ai-dev-baseline — codex adapter.
#
# Wires this repo's Codex payload (agents/codex/AGENTS.md, generated by
# scripts/build.sh from base/practices/ — never edit it by hand) into Codex's
# user-global root config. Codex auto-loads ~/.codex/AGENTS.md at the start of
# every session (base/roles.md: "codex reads ~/.codex/ + AGENTS.md").
#
# Called by the top-level installer/uninstaller — do not run standalone unless
# you know what you're doing:
#   bash agents/codex/adapter.sh install   <repo> <backup_dir>
#   bash agents/codex/adapter.sh uninstall <repo>
#
# Portable to macOS bash 3.2: no `readlink -f`, no `mapfile`, no associative
# arrays.

set -uo pipefail

# Shared symlink/backup primitives (adb_info / adb_link / adb_unlink_if_ours) — the
# ONE home, sourced not copied. This adapter lives at agents/codex/adapter.sh, so the
# repo's scripts/lib is two levels up.
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
. "$_here/../../scripts/lib/common.sh"

cmd_install() {
  local repo="$1" backup_dir="$2" rc=0
  mkdir -p "$HOME/.codex"
  # Link via the shared manifest (#48) — the same producer install.sh + bin/baseline consume,
  # so this adapter can't drift from them. Capture the status BEFORE the note print (adb_info
  # would otherwise overwrite $?), so a missing source makes the adapter — and the top-level
  # installer — exit non-zero.
  adb_link_manifest "$backup_dir" <<EOF || rc=1
$(adb_agent_manifest codex "$repo" "$HOME")
EOF
  adb_info "  note   ~/.codex/config.toml (model, reasoning effort, sandbox/approval policy) is yours to manage — sample at agents/codex/config.toml.sample"
  return "$rc"
}

cmd_uninstall() {
  local repo="$1"
  adb_unlink_if_ours "$HOME/.codex/AGENTS.md" "$repo"
}

case "${1:-}" in
  install)
    shift
    if [ $# -lt 2 ]; then
      echo "usage: adapter.sh install <repo> <backup_dir>" >&2
      exit 2
    fi
    cmd_install "$1" "$2"
    ;;
  uninstall)
    shift
    if [ $# -lt 1 ]; then
      echo "usage: adapter.sh uninstall <repo>" >&2
      exit 2
    fi
    cmd_uninstall "$1"
    ;;
  *)
    echo "usage: adapter.sh <install|uninstall> ..." >&2
    exit 2
    ;;
esac
