#!/usr/bin/env bash
# ai-dev-baseline — codex adapter.
#
# Wires this repo's Codex payload (agents/codex/AGENTS.md, generated by
# scripts/build.sh from base/practices/ — never edit it by hand) into Codex's
# user-global root config. Codex auto-loads ~/.codex/AGENTS.md at the start of
# every session (base/roles.md: "codex reads ~/.codex/ + AGENTS.md").
#
# Called by the top-level installer/uninstaller — do not run standalone unless
# you know what you're doing:
#   bash agents/codex/adapter.sh install   <repo> <backup_dir>
#   bash agents/codex/adapter.sh uninstall <repo>
#
# Runs on bash >= 5.3 (this repo's runtime floor — #255). It gates its own interpreter via
# adb_require_bash below, so an adapter invoked from a shell whose PATH resolves an older
# bash re-execs into a current one rather than failing somewhere deep.

set -uo pipefail

# Shared symlink/backup primitives (adb_info / adb_link / adb_unlink_if_ours) — the
# ONE home, sourced not copied. This adapter lives at agents/codex/adapter.sh, so the
# repo's scripts/lib is two levels up.
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
. "$_here/../../scripts/lib/common.sh"
# bash 5.3 runtime floor (#256) — re-exec into a >= 5.3 interpreter, or exit with instructions.
adb_require_bash "$@"

cmd_install() {
  local repo="$1" backup_dir="$2" rc=0 manifest
  mkdir -p "$HOME/.codex"
  # Link via the shared manifest (#48) — the same producer install.sh + bin/baseline consume,
  # so this adapter can't drift from them. Capture the status BEFORE the note print (adb_info
  # would otherwise overwrite $?), so a missing source makes the adapter — and the top-level
  # installer — exit non-zero.
  #
  # THE PRODUCER IS CAPTURED SEPARATELY (#324, D64): a `$(…)` inside the heredoc discarded its
  # status, so its refusal for an unrepresentable $repo/$HOME arrived as an empty manifest.
  manifest="$(adb_agent_manifest codex "$repo" "$HOME")" || {
    adb_info "  ERROR  cannot enumerate the install surface — nothing was linked (see above)"
    return 1
  }
  adb_link_manifest "$backup_dir" <<EOF || rc=1
$manifest
EOF
  adb_info "  note   ~/.codex/config.toml (model, reasoning effort, sandbox/approval policy) is yours to manage — sample at agents/codex/config.toml.sample"
  return "$rc"
}

cmd_uninstall() {
  local repo="$1" manifest
  # Remove via the same shared manifest install linked from (#48), so this can't drift from
  # cmd_install even if codex ever grows a second installed path. Same capture-then-check as
  # cmd_install — and a refusal removes NOTHING rather than acting on a map it just rejected.
  manifest="$(adb_agent_manifest codex "$repo" "$HOME")" || {
    adb_info "  ERROR  cannot enumerate what to remove — NOTHING was unlinked (see above)"
    return 1
  }
  adb_unlink_manifest "$repo" <<EOF
$manifest
EOF
}

case "${1:-}" in
  install)
    shift
    if [ $# -lt 2 ]; then
      echo "usage: adapter.sh install <repo> <backup_dir>" >&2
      exit 2
    fi
    cmd_install "$1" "$2"
    ;;
  uninstall)
    shift
    if [ $# -lt 1 ]; then
      echo "usage: adapter.sh uninstall <repo>" >&2
      exit 2
    fi
    cmd_uninstall "$1"
    ;;
  *)
    echo "usage: adapter.sh <install|uninstall> ..." >&2
    exit 2
    ;;
esac
