#!/usr/bin/env bash
# ai-dev-baseline — codex adapter.
#
# Wires this repo's Codex payload (agents/codex/AGENTS.md, generated by
# scripts/build.sh from base/practices/ — never edit it by hand) into Codex's
# user-global root config. Codex auto-loads ~/.codex/AGENTS.md at the start of
# every session (base/roles.md: "codex reads ~/.codex/ + AGENTS.md").
#
# Called by the top-level installer/uninstaller — do not run standalone unless
# you know what you're doing:
#   bash agents/codex/adapter.sh install   <repo> <backup_dir>
#   bash agents/codex/adapter.sh uninstall <repo>
#
# Portable to macOS bash 3.2: no `readlink -f`, no `mapfile`, no associative
# arrays.

set -uo pipefail

info() { printf '%s\n' "$*"; }

# Back up an existing real path (unless it's already our correct symlink),
# then symlink. Mirrors install.sh's link() so backups land in the same
# mirrored-absolute-path shape under backup_dir.
link() {
  local src="$1" dest="$2" backup_dir="$3"
  if [ -L "$dest" ]; then
    if [ "$(readlink "$dest")" = "$src" ]; then
      info "  ok     ${dest/#$HOME/~}"
      return
    fi
    rm -f "$dest"
  elif [ -e "$dest" ]; then
    mkdir -p "$backup_dir$(dirname "$dest")"
    mv "$dest" "$backup_dir$dest"
    info "  backup ${dest/#$HOME/~} → ${backup_dir/#$HOME/~}$dest"
  fi
  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  info "  link   ${dest/#$HOME/~} → ${src/#$HOME/~}"
}

# Remove dest only if it is a symlink pointing back inside repo.
unlink_if_ours() {
  local dest="$1" repo="$2"
  if [ -L "$dest" ]; then
    case "$(readlink "$dest")" in
      "$repo"/*)
        rm -f "$dest"
        info "  unlink ${dest/#$HOME/~}"
        ;;
      *)
        info "  skip   ${dest/#$HOME/~} (not ours)"
        ;;
    esac
  else
    info "  skip   ${dest/#$HOME/~} (not a symlink)"
  fi
}

cmd_install() {
  local repo="$1" backup_dir="$2"
  mkdir -p "$HOME/.codex"
  link "$repo/agents/codex/AGENTS.md" "$HOME/.codex/AGENTS.md" "$backup_dir"
  info "  note   ~/.codex/config.toml (model, reasoning effort, sandbox/approval policy) is yours to manage — sample at agents/codex/config.toml.sample"
}

cmd_uninstall() {
  local repo="$1"
  unlink_if_ours "$HOME/.codex/AGENTS.md" "$repo"
}

case "${1:-}" in
  install)
    shift
    if [ $# -lt 2 ]; then
      echo "usage: adapter.sh install <repo> <backup_dir>" >&2
      exit 2
    fi
    cmd_install "$1" "$2"
    ;;
  uninstall)
    shift
    if [ $# -lt 1 ]; then
      echo "usage: adapter.sh uninstall <repo>" >&2
      exit 2
    fi
    cmd_uninstall "$1"
    ;;
  *)
    echo "usage: adapter.sh <install|uninstall> ..." >&2
    exit 2
    ;;
esac
